# Generated by Django 5.2.7 on 2025-10-30 14:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(default="Smart Irrigation Device", max_length=100),
                ),
                (
                    "device_id",
                    models.CharField(
                        help_text="Unique ID from ESP32, e.g., MAC or custom",
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="devices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Device",
                "verbose_name_plural": "Devices",
            },
        ),
        migrations.CreateModel(
            name="CurrentStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("current_moisture", models.FloatField(default=0)),
                ("pump_status", models.BooleanField(default=False)),
                (
                    "last_updated",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "device",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="current_status",
                        to="dashboard.device",
                    ),
                ),
            ],
            options={
                "verbose_name": "Current Status",
                "verbose_name_plural": "Current Statuses",
            },
        ),
        migrations.CreateModel(
            name="PumpCommand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[("ON", "Turn Pump ON"), ("OFF", "Turn Pump OFF")],
                        max_length=3,
                    ),
                ),
                (
                    "triggered_by",
                    models.CharField(
                        default="manual",
                        help_text="manual, auto, or api",
                        max_length=20,
                    ),
                ),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commands",
                        to="dashboard.device",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pump Command",
                "verbose_name_plural": "Pump Commands",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="SensorReading",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "moisture_level",
                    models.FloatField(help_text="Soil moisture percentage (0-100)"),
                ),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="readings",
                        to="dashboard.device",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sensor Reading",
                "verbose_name_plural": "Sensor Readings",
                "ordering": ["-timestamp"],
            },
        ),
    ]
