# Generated by Django 5.2.7 on 2025-10-30 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="api_key",
            field=models.CharField(
                default="1b8e380d74dfc0c44384ab02c973a84a5da23a5e5ce19909edf15de297317fd3",
                max_length=64,
                unique=True,
            ),
        ),
    ]
