# Generated by Django 5.2.7 on 2025-10-31 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0002_device_api_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="currentstatus",
            name="auto_mode",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="pumpcommand",
            name="acknowledged",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="device",
            name="api_key",
            field=models.CharField(
                default="2e0ea8fff64aab5129c3910e56edfbb2b5a3899a401b721dd894c6e34d23bb40",
                max_length=64,
                unique=True,
            ),
        ),
    ]
